namespace LoLUpdater
{
partial class Form1
{
private System.ComponentModel.IContainer components = null;
protected override void Dispose(bool disposing)
{
if (disposing && (components != null))
{
components.Dispose();
}
base.Dispose(disposing);
}
#region Windows Form Designer generated code
private void InitializeComponent()
{
this.components = new System.ComponentModel.Container();
System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
this.groupBox1 = new System.Windows.Forms.GroupBox();
this.checkBox8 = new System.Windows.Forms.CheckBox();
this.checkBox1 = new System.Windows.Forms.CheckBox();
this.checkBox3 = new System.Windows.Forms.CheckBox();
this.checkBox4 = new System.Windows.Forms.CheckBox();
this.radioButton1 = new System.Windows.Forms.RadioButton();
this.groupBox2 = new System.Windows.Forms.GroupBox();
this.radioButton3 = new System.Windows.Forms.RadioButton();
this.radioButton2 = new System.Windows.Forms.RadioButton();
this.button1 = new System.Windows.Forms.Button();
this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
this.groupBox4 = new System.Windows.Forms.GroupBox();
this.button2 = new System.Windows.Forms.Button();
this.checkBox7 = new System.Windows.Forms.CheckBox();
this.checkBox2 = new System.Windows.Forms.CheckBox();
this.checkBox5 = new System.Windows.Forms.CheckBox();
this.checkBox6 = new System.Windows.Forms.CheckBox();
this.groupBox3 = new System.Windows.Forms.GroupBox();
this.groupBox1.SuspendLayout();
this.groupBox2.SuspendLayout();
this.groupBox4.SuspendLayout();
this.groupBox3.SuspendLayout();
this.SuspendLayout();
this.groupBox1.Controls.Add(this.checkBox8);
this.groupBox1.Controls.Add(this.checkBox1);
this.groupBox1.Controls.Add(this.checkBox3);
this.groupBox1.Controls.Add(this.checkBox4);
this.groupBox1.Location = new System.Drawing.Point(0, 0);
this.groupBox1.Name = "groupBox1";
this.groupBox1.Size = new System.Drawing.Size(101, 108);
this.groupBox1.TabIndex = 1;
this.groupBox1.TabStop = false;
this.groupBox1.Text = "Options";
this.checkBox8.AutoSize = true;
this.checkBox8.Location = new System.Drawing.Point(6, 85);
this.checkBox8.Name = "checkBox8";
this.checkBox8.Size = new System.Drawing.Size(71, 17);
this.checkBox8.TabIndex = 4;
this.checkBox8.Text = "Trim SSD";
this.checkBox8.UseVisualStyleBackColor = true;
this.checkBox1.AutoSize = true;
this.checkBox1.Location = new System.Drawing.Point(6, 20);
this.checkBox1.Name = "checkBox1";
this.checkBox1.Size = new System.Drawing.Size(79, 17);
this.checkBox1.TabIndex = 0;
this.checkBox1.Text = "Clean temp";
this.checkBox1.UseVisualStyleBackColor = true;
this.checkBox3.AutoSize = true;
this.checkBox3.Location = new System.Drawing.Point(6, 42);
this.checkBox3.Name = "checkBox3";
this.checkBox3.Size = new System.Drawing.Size(92, 17);
this.checkBox3.TabIndex = 2;
this.checkBox3.Text = "Uninstall PMB";
this.checkBox3.UseVisualStyleBackColor = true;
this.checkBox4.AutoSize = true;
this.checkBox4.Location = new System.Drawing.Point(6, 64);
this.checkBox4.Name = "checkBox4";
this.checkBox4.Size = new System.Drawing.Size(85, 17);
this.checkBox4.TabIndex = 3;
this.checkBox4.Text = "Defrag HDD";
this.checkBox4.UseVisualStyleBackColor = true;
this.radioButton1.AutoSize = true;
this.radioButton1.Checked = true;
this.radioButton1.Location = new System.Drawing.Point(6, 19);
this.radioButton1.Name = "radioButton1";
this.radioButton1.Size = new System.Drawing.Size(74, 17);
this.radioButton1.TabIndex = 2;
this.radioButton1.TabStop = true;
this.radioButton1.Text = "Patch LoL";
this.radioButton1.UseVisualStyleBackColor = true;
this.groupBox2.Controls.Add(this.radioButton3);
this.groupBox2.Controls.Add(this.radioButton1);
this.groupBox2.Controls.Add(this.radioButton2);
this.groupBox2.Location = new System.Drawing.Point(6, 0);
this.groupBox2.Name = "groupBox2";
this.groupBox2.Size = new System.Drawing.Size(118, 108);
this.groupBox2.TabIndex = 3;
this.groupBox2.TabStop = false;
this.groupBox2.Text = "Main function";
this.radioButton3.AutoSize = true;
this.radioButton3.Location = new System.Drawing.Point(6, 65);
this.radioButton3.Name = "radioButton3";
this.radioButton3.Size = new System.Drawing.Size(107, 17);
this.radioButton3.TabIndex = 4;
this.radioButton3.Text = "Only checkboxes";
this.radioButton3.UseVisualStyleBackColor = true;
this.radioButton2.AutoSize = true;
this.radioButton2.Location = new System.Drawing.Point(6, 42);
this.radioButton2.Name = "radioButton2";
this.radioButton2.Size = new System.Drawing.Size(106, 17);
this.radioButton2.TabIndex = 3;
this.radioButton2.Text = "Restore backups";
this.radioButton2.UseVisualStyleBackColor = true;
this.button1.Location = new System.Drawing.Point(6, 114);
this.button1.Name = "button1";
this.button1.Size = new System.Drawing.Size(174, 20);
this.button1.TabIndex = 4;
this.button1.Text = "OK";
this.button1.UseVisualStyleBackColor = true;
this.button1.Click += new System.EventHandler(this.button1_Click);
this.groupBox4.Controls.Add(this.groupBox1);
this.groupBox4.Controls.Add(this.groupBox3);
this.groupBox4.Location = new System.Drawing.Point(125, 0);
this.groupBox4.Name = "groupBox4";
this.groupBox4.Size = new System.Drawing.Size(228, 108);
this.groupBox4.TabIndex = 6;
this.groupBox4.TabStop = false;
this.button2.Location = new System.Drawing.Point(186, 114);
this.button2.Name = "button2";
this.button2.Size = new System.Drawing.Size(173, 20);
this.button2.TabIndex = 7;
this.button2.Text = "Self-Elevate";
this.button2.UseVisualStyleBackColor = true;
this.button2.Click += new System.EventHandler(this.button2_Click);
this.checkBox7.AutoSize = true;
this.checkBox7.Location = new System.Drawing.Point(6, 41);
this.checkBox7.Name = "checkBox7";
this.checkBox7.Size = new System.Drawing.Size(106, 17);
this.checkBox7.TabIndex = 6;
this.checkBox7.Text = "Windows update";
this.checkBox7.UseVisualStyleBackColor = true;
this.checkBox2.AutoSize = true;
this.checkBox2.Location = new System.Drawing.Point(6, 18);
this.checkBox2.Name = "checkBox2";
this.checkBox2.Size = new System.Drawing.Size(122, 17);
this.checkBox2.TabIndex = 1;
this.checkBox2.Text = "Clean update cache";
this.checkBox2.UseVisualStyleBackColor = true;
this.checkBox5.AutoSize = true;
this.checkBox5.Location = new System.Drawing.Point(6, 64);
this.checkBox5.Name = "checkBox5";
this.checkBox5.Size = new System.Drawing.Size(112, 17);
this.checkBox5.TabIndex = 7;
this.checkBox5.Text = "Windows services";
this.checkBox5.UseVisualStyleBackColor = true;
this.checkBox6.AutoSize = true;
this.checkBox6.Location = new System.Drawing.Point(6, 85);
this.checkBox6.Name = "checkBox6";
this.checkBox6.Size = new System.Drawing.Size(112, 17);
this.checkBox6.TabIndex = 8;
this.checkBox6.Text = "Mouse polling rate";
this.checkBox6.UseVisualStyleBackColor = true;
this.groupBox3.Controls.Add(this.checkBox6);
this.groupBox3.Controls.Add(this.checkBox5);
this.groupBox3.Controls.Add(this.checkBox2);
this.groupBox3.Controls.Add(this.checkBox7);
this.groupBox3.Location = new System.Drawing.Point(104, 0);
this.groupBox3.Name = "groupBox3";
this.groupBox3.Size = new System.Drawing.Size(130, 108);
this.groupBox3.TabIndex = 5;
this.groupBox3.TabStop = false;
this.groupBox3.Text = "Admin Options";
this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
this.ClientSize = new System.Drawing.Size(362, 141);
this.Controls.Add(this.button2);
this.Controls.Add(this.groupBox4);
this.Controls.Add(this.button1);
this.Controls.Add(this.groupBox2);
this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
this.MaximizeBox = false;
this.Name = "Form1";
this.Text = "LoLUpdater";
this.Load += new System.EventHandler(this.Form1_Load);
this.groupBox1.ResumeLayout(false);
this.groupBox1.PerformLayout();
this.groupBox2.ResumeLayout(false);
this.groupBox2.PerformLayout();
this.groupBox4.ResumeLayout(false);
this.groupBox3.ResumeLayout(false);
this.groupBox3.PerformLayout();
this.ResumeLayout(false);
}
#endregion
private System.Windows.Forms.GroupBox groupBox1;
private System.Windows.Forms.CheckBox checkBox4;
private System.Windows.Forms.CheckBox checkBox3;
private System.Windows.Forms.CheckBox checkBox1;
private System.Windows.Forms.RadioButton radioButton1;
private System.Windows.Forms.GroupBox groupBox2;
private System.Windows.Forms.RadioButton radioButton3;
private System.Windows.Forms.RadioButton radioButton2;
private System.Windows.Forms.Button button1;
private System.Windows.Forms.ToolTip toolTip1;
private System.Windows.Forms.GroupBox groupBox4;
private System.Windows.Forms.Button button2;
private System.Windows.Forms.CheckBox checkBox8;
private System.Windows.Forms.CheckBox checkBox7;
private System.Windows.Forms.CheckBox checkBox2;
private System.Windows.Forms.CheckBox checkBox5;
private System.Windows.Forms.CheckBox checkBox6;
private System.Windows.Forms.GroupBox groupBox3;
}
}