#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-LoLUpdater_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$LoLUpdater = New-Object 'System.Windows.Forms.Form'
	$buttonNothing = New-Object 'System.Windows.Forms.Button'
	$buttonRestore = New-Object 'System.Windows.Forms.Button'
	$buttonPatch = New-Object 'System.Windows.Forms.Button'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$checkboxCleanTemp = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxWindowsUpdate = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxDeleteOldLogs = New-Object 'System.Windows.Forms.CheckBox'
	$checkboxDefrag = New-Object 'System.Windows.Forms.CheckBox'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$LoLUpdater.SuspendLayout()
	$groupbox1.SuspendLayout()
	#
	# LoLUpdater
	#
	$LoLUpdater.Controls.Add($buttonNothing)
	$LoLUpdater.Controls.Add($buttonRestore)
	$LoLUpdater.Controls.Add($buttonPatch)
	$LoLUpdater.Controls.Add($groupbox1)
	$LoLUpdater.ClientSize = '153, 218'
	$LoLUpdater.FormBorderStyle = 'FixedSingle'
	#region Binary Data
	$LoLUpdater.Icon = [System.Convert]::FromBase64String('
AAABAAYAMDAAAAEACACoDgAAZgAAACAgAAABAAgAqAgAAA4PAAAQEAAAAQAIAGgFAAC2FwAAMDAA
AAEAIACoJQAAHh0AACAgAAABACAAqBAAAMZCAAAQEAAAAQAgAGgEAABuUwAAKAAAADAAAABgAAAA
AQAIAAAAAAAACQAAAAAAAAAAAAAAAQAAAAEAAAAAAAAFBgsABgoMAAgIDgAFFAsACBAPAAQaDAAI
GQ8ABw8QAAoKEwANDRoABxURAAkUFAAGGxEACRkRAAkZFQANGxYACxwXAA0cFgAOEhsADBkaAAod
GAAOHRgADhgcAA0dHAAQEB4AEBwcAAMjDAAELA8ABiERAAsiFQAELRAACCsVAAohGQAOIRkACiYZ
AA0mGAAMIBwADiUcAAcvGgAKKRoADikZAA8rHQAKLRwADi8cABAhHAARKhwABTISAAgzFwAFOhUA
CDgVAAozGgAGPxgACTsbABIyHQAROx4AEhMjABIZIgAWFikAFhgqABgYLQAaGjEAEy0gABQuIgAS
MyAAFTEiABU0IwAWMiQAFjQlABg0JgAWOCUAFz8nABg5JwAYNSgAGDkpABk9KgAEQRQABkQaAApE
HAAFShkACEseAAVUGgAIUB8ABlkcAAhcHgALRSEAB04hAAxLIgAQQCEAEEQiABZAJQASRSUAFUYk
ABlDJwASSSQAFUYoABlBKQAYRikAG0EtABpGLQAdRi4AFkkoABhKKgAYTCoAGkgsABlOLAAHVyEA
C1MhAApcIgASUSUAFlUsABlTLQAVWywAGVguAB1DMAAdRjAAHkgxAB5JNAAZVzAAG1ozACBJMwAg
STQAIE42ACBdMgAiUzoACWMhAAdvIQAJayUADGQqAAltKAASYywAFW0uABhpLwAHdSUACHMkAAd7
JQAIeSQADnMtAAp6KgAVcy4AEHotABZkMAAeZDQAFm8xABhtMQATdTEAG3E1ABJ7MgAdeDYAIGY3
ACNoNwAkZzgAIW05ACB0NwAhcDkAI3s9ACt+QwAIgicACoMqAAmLKgAJkiwACpkuAA2LMQAVhjUA
EoszABaDOgAcgTsAF487ABuMOwALljAADJoyABGUNQARmzUAFpY8ABuUPgATnDgAGZw/ACCCPgAM
ojUAC6o1AA2mOAANrToAFqM7ABWqPgANsjsAEbI/ABaXQAAclEIAHJxAACOFQQAqh0UAJYpDACmM
RgAhlEMAI5tGACmUSAAmmUoAKJpLADCQSwAcpEEAFq5BAByrQgAfrkgAFrFCABuyRAAQuEEAG7tG
AB+3TwAbukkAIaBEACqjTQAgskYAIbVJACmxTgAiu0wAKbpPAC2iUAAvrlIAMqNRADSsVQAlvFAA
K7tTADC/VwA3tloAN7laAA/EQwAQxUMAFclLAB/GUAAdzVEAIsNNACXDUQAsw1UAJMlTACrKVgAt
xlgALsxZADPCWwAxzlwAIdFXACbTWQAt1FsALthdADLRXQAx2F4APcpkADXTYQA71GQAM9pjAD3Y
ZwA732gAQtxsAELjbQBH53IASul2AP///wB1dXV0c3Nzc3Nzc3N1dXVzc3Nzc3N4dXNzc3Nzc3h1
dXNzc3Nzc3Nzc3Nzc3N1enx1c0ZCQkJCP0JCP0JCQ0NDQ0hdc2FzdHRzc3R0dHNzc11IQkJCQkJC
QkI/QkJLc3hzQj8WEBAQEBAQEBYWFhYiIiw3VVtbXl5eXl5eXF5dXUY+IhAWFhYWFhAQECI/S3hz
QhYCAQEBAQEBAQIDAgICBB0yTk5OXl5eXl5cXFxbXTYiAgIBAQEBAQEDAwIiQ3VzQhYBAQEBAQEB
AQEBAQECAh0yTmtsgoOPmY+PkHFeNykQAgEBAQEBAQEBAQIiQ3RzQhYBAQEBAQEBAQEBAQECBB0y
TWyRpK7C0sXBqIttLCIEAgEBAQEBAQEBAQIiQ3RzQhYBAQEBAQEBAQEDCQMDCR0yTYGry9br9uvX
yqZsIAYEAgMDAwEDAQEBAQIiQ3RzQhYBAQEBAQEBAQkJAwkJCR0gNH2kyNDp8ufKvJFeIgQMCQkD
AgMBAQEBAQIiQ3hzQhABAQEBAQECAwkJCQkJCQ8dIGqKrLfO5cytjGw3HQwJCQkJCQkDAwEBAQIi
Q3hzQhYDAQEBAgMCCQkJCgoKCgwPHU5/n7K44rKKa1UoDAoKCQkJCQkCCQMBAwIiQ3hzQhYBAQEB
AwMJCQkJCgoKCgoJHTRUnqG44ayBTScVCgoKCgoJCQkJAwEDAQIiSXhzQhYDAQEBAwMDCQkJCQoZ
GQoJCjR9nay4462ANSgYOAoKCgoKCQkDAQkBAQIWQ3hzRRYBAQEBAwMDCQkJCRkZOAoKFjd9nazL
5bqAKBg4ODg4CgoJCQMJAQEBAwIiSXNzRRYBAQEBAQMDCQkJCgo4ODgKCjRUna/Q77pwGBY4GDo4
CgoKCQkBCQMBAQMWQ3hzRRYJAQEBAQMJCQoKGTg4ODgKEDRUna/Q8LtwFQoYPDo4GQoJCQkJCQMD
AQIiSXNzRRYDAQEBAwkKChkZODg8OjgJDCx9nq/Q8btuDAo6PDw4GRkZCgkKCQkJAwkiSXhzQhYJ
AQEBAQkKGRk4ODw8OjgKDzVUna/W8cFuDwo4PDw4OBkKGQoJCQkJAwIiSXhzRRYJCQEBAwkZGTg4
ODw8PDgJCTRUnrbW+MJuDAo5PDw4OBkZCRkKCgkJCQkiSXh1QxYJAQEBCQkKODg4Ojo8PDgKDzVU
nbbc+MF3DAo4PDw6OBkZGQkZCQkJCQktSXh1SSIJCQEBAwoZGTg4PDw9PDgJDzJ9n7bn+MV2ChY4
PDw6OBkZGRkJGQkJCQkiS3h1QyIJAwEBCQkZODg4PDw9PTgKCTR9n7bc+MV3DBk4PDw6ODgZGRkT
CQoJCQwtSXh4SS0JCQMBCQoZGTg8ODw9PTgKDDd9n7fn+MVwChk5PT08OjgZGQoKCgoJCQkiSXh1
SSIJAwEDCQkZODg6PDw9PTg4DE19oLbn+MV2EAo8PT08OjoZGRkKCgoJCQktS3h1SRYJCQMBAQoZ
ODo6Ojw9PTg4FlV/n8jn+MV2Cjk8PT08Ohk4GQoTCgoJCQwiSXhzQyIJAgMBCQkZGTg6Ojw9PTwZ
FlV/oMjc+MV3OTg8PT08OjoZGRkKCgoJCQktSXhzSRYJCQEBCQkZODg6Ojw9PDw5GFWBoMjW9MV3
OTk8PT09ORkZGQoKCgoCCQktS3hzQxYJCQEBCQkZGRk6Ojw8PDk5JVWBoLfn9MV3OTk8PT08OhkZ
GQoKCgkKAhMiSXh4SRYJAQEBAwkZGTg4PDo8PDk5JVeBoLfn+MV3OTg8PT08GRkZCgoKAgoCCQki
SXhzSRYCAQEBAwkKGRk4ODw8PDkWFld/oLfn+MV3OTg8PT05GRkKCgkKCgkJCQkiSXhzSRYJAgEB
AwkKGRkZOjg4ODk4JVaGoLfn+MV3ORk5PDw6GRkKCQoCCgkJAgkiSXh4QyIEAgEBAQkJChkZODg8
ODkWJVCGoMvn+MV3Fjg4PDk6GRkKCQkJAgUJAgktQ3h1QyIEAgIBAwkKChkZGRk4OBYWKFCGobfp
+MV3Chk5Ojo6GRkZCQkJBAUJAgktSHh0QyIEDCIgLiUWFhY4GTk5ORYWJ1CFrMvn+sWOIhY4OTk4
FhkWFiIlPikSBQktSHh0RiIEIk5xcXRbST8iLS05FiUlMmqFrMzp+tqVPxYtOSI5IiUuNTRbXFxB
EgIWSHhzQiIEMHG/vY97dFtCLi4lJS4gMmqKrMzu+tuYQi0/IiIlLixNVmqOmpddEAIWSHhzQhAE
MIK7wb6bmo53bmdnV1dXan+fstDu/d++dml0XmdeV2psiZOxvpxvIgIWSHhzQhAEHW2TvcLCxcO+
v7+9saaTnqSsstb2/fXbvr+9sbGlsaW6usLF2MZ7PgIWRXhzQhABG1B/pNHe7e3t7e3e3crQtbW0
tOT2/fv39e3e3dzPz8/P1ufd4NqXKQISQXhzQhABBjFUjLzd7O729vHu7OXQzbi0s87s+/n39vbp
7unp5+Xk5Ofs7duZNgISQXRzQhABBjJPf6PHytTU1NTQzMu3srKhobbU3dfWytbU1MzMyMjMy9TX
3tuZNwQtSHRzQhABBBsxUYakq6ysrKysrKypoKCgn6CrrLysr6ysrKysqayhrK/L19WTNxIuSHhz
QhABBAYcTFR+iIiIiJ2InYiIiIiGhoaIiIiInYidiJ2IiIiIiJ+vydGQNxIuSHhzQhABBAQbHExR
UVFTUVFTUVFRUVFRT1FRUVFRUVNRU1FRUVFRU1R9i5BtIAcpN3hzQhABAQQEBhscHBwyIBwyHCAg
HBwcHBwcHBwcHBwcHBwcIBwcHDIwNDccBwcpSHhzQyICBAEEBAYGGwYGBAQEBAQGBAQEBAQEBAQG
BAYGBAYEBAQEBAQGBwcHBwcpQXR4Sz8WECIiHSkgPiAiICIiICIgJS4iLiIuIi4iPiIgIj4iICIg
JSApKSAgEilBXXh1c0tIQ0Y2SEhISEhGRkZGSEZISEZGRkZGSEZGRkhISEJGSEhGSEhGSEhIN0hd
eHN6eHh4dXR1dHR0dHR0dHR1dHV1dHV0dHR1eHV0dHR0eHV1dXR0dHR0dHR0eHhzc3UAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAIAAAAEAAAAABAAgAAAAAAAAE
AAAAAAAAAAAAAAABAAAAAQAAAAAAAAUGCwAGBgwABQgLAAQMCwAGCA0ABw8NAAgIDgAIDw8ABREL
AAQUCwAGEQ0ABRUMAAQaCwAFGg0ABB0MAAgZDwAJCREACQ0TAAoKFQAKDBUADAwXAAsPGAANDRkA
Dg4cAAkSEQAJFRIACxAWAAcZEQAIGBIACB0RAAsYFAAMGBYADBEZAAwWGAAPER0ADxYdAA0ZGQAK
HhgADB4ZAA4ZHAAPHR0AEBAeABAUHgADIQ0ABSgPAAYjEAAKIhQABigTAActFgAILxcADiIZAA4l
GgAKKRgADigaAA4tGgAPKhwADS0cABAjGwAQJBsAESIeABAlHAARKR0AES0eAAMxEAAHMBcABjUV
AAgxFwAEOBIABzgWAAc8FgAIPBcACTAZAA0wGgALNxsADjUbAA8wHQAKNh0ACzoaAAs4HwAKPR0A
DT0eABI0HgARESEAERUiABMTJAATFCUAFBQmABAZIQATGCQAFBglABYWKQAXFywAFhgpABgYLQAZ
GTAAEiggABMtIAAOPSAAFjYlABI9IwARPyQAFT4kABg7JgAYPicAFj4oABo+KwAaPywABEUWAAVI
FwAHRRsACEIdAApFHQAGSxgABk4ZAAdMHQAJUh8ABlocAAxNIAANTSUAEkAiABFFIgATQSYAFUIl
ABJFJQAWTicAFUIoABZGKAAaQCsAGkQqABpBLQAcQi4AGUQtABxFLgAWSCgAHE4sAAtXIAAJWiIA
CFwhAApZJAARUSYAFlEpABRWKQAZUioAE14pABtaLgAcQjAAHUYwAB1IMgAfSjQAHFUwABtbMQAg
TjYACGkhAAhsIwAKaSUADm0rABdiLQAIcCQACXQmAAl7JgAIfCYADXYqAAl4KAAQci0AHGg0ABdx
MQATezIAIWw4ACF6PAAoeT8ACIEmAAqCKQALhSkADYQsAAqKKwAMki8ACZYuAA6KMQAWgzYAHIU7
ABqLPAAOkjIADpQzAA2bMgARkDYAEZY0ABGaNAARnjYAF5U7ABmTOwASmzgAGZ4+ACKEPwANojYA
Dqw5ABGhOAARpDoAE6c8ABinPwAVqT0ADbE8AA64PgAdkkEAIo5CACOWRQAqm0sAMJxPABmiRAAW
rkEAGapBABusQgAYqUYAHaxEAB2pSQAWt0IAGrVFABy3RwAXuEUAGbxJACCmRwAiqUcAKqVOACKp
SgAnrU4AKKxPACOwSQAmuU0AK65SAC6xUwAzsFYANblZAB7BTQAfxU0AH8NQACLCTwAiwlAAJ8RS
ACfFVAAtwFYAKcZVACjJVgApzFcAL8NYAC3JWQArzVgAOsNfADHLXAAu0VwANc5gADbUYQA50mMA
O9lmAEHXagBA22oA////AJSSgoJqampqgoJqgoKFlJKUgpSSlIKCgoKCgoJqgpKYgmM7MzMzMzs7
OztMeHiGhoaGhoaCf2E7Ozs7MzM7Z5KCOwMDAwMDAwMDBA5HdnaMjo6OjHhMIAQDAwMDAwQ7goI7
AwMDAwMDAwMEHEZ0pLPMzLSmhjcJAQMDAwMDAzuCgjsDAwMDAwMCAgIgRoq/2fX14rVwDgkHAQMD
AwMDO4KCMwMDAwMDAgIXAiIwc7LI6ei+nEwgEhICAgIDAwM7goI7AwMDAwIXFxcYGBxCnrHKw5tw
LxIYEhIVAgIBAzuSgjsDAwMCAgIXFxgYEkGbsMrGi0goGBgYAhcCAgEBO5KCOwMDAwICFwIXUxgY
SJuw29R2KFRUUxgSAgICAhI7goI7AwMDAgIVGFNTVBhDmbbp1ngoWF1TGAIXFwIBATuCgjsBAwMC
UxhTVV1VEjWbsezfeBhdXVRTUxUXAhUSO5KCOwICAgJTU1NVX1USQZm28OFlFlRfU1MYGBgCFQJg
koI7EgMCFxdTVV9fVRgxm7vw4XohVF9dGBcYGAIXEjuSgjsCAgIXU1NVX19VEjGbu/HkeiFdX1RT
UxcYFwIXYJKSYBICAhcXU1VcX1UYNZ7E8eR6F11fX1RTFxgXEhU7kpI7AhcCFxhVXFxfVVRHn8bw
5IAhX19fU1MXGBgCGGGCamASAwICU1NcXF9fIU+fxuzkglleX19UF1MYGBICYJJqOwICAhdTU11V
X11UT6PG8OR6WV5fXypUFxgCGBJggoJgAgICAlNTVVxfVCRlo7zx5ZJZXV9UFxcXEhgBEjuSajsS
AwICF1NTVVVUKEejxfHlelRdX1RUFwIYAhICYJKSOwQDAwIYGFNTXVQoZavF8uV6VFRdVFMXAhIS
EhJgkoI7IiIgKCEoF1RUKC9vq8b15YYoVFlUFyQkJC8iAWCSgmEKR6WXhmM7OygzNXOr0vjnljtg
JDs7R3CPj2EHYJJqMy6My8Gol4Z6Z2VvirLR+vaoempnZXCLnKmqZgk7koIzCkenzOHezs7Ny7G5
wtH8/ubOzczLy9Dc3s+FIDuSgjMEQpu+8PP59/Xs2cnD1/r++/nx8urq6ezw5pEOO4KCMwQtcp/A
1NTU1MjFvLG81OLU1NTIyMbI1OPmnS9hgoIzBA5GdaOtra+vraurq5+tra6ur6+tra2uyN2QNmGS
gjMECg5AbWxxbXFtbGxsbGxsbW1tbGxsbHR1kUcOYYJqOwQECg4uLi4ODg4ODg4ODg4uDw4uDg4O
Di4vHg5hgpJnOzs2NUxIYTdhYTY1YTVhYTVhNmE1YTVITEw2YWaClJKCgoKCgpKCaoKCgoWCgoKC
goKCgoKCgpKCgoKCkpUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAQAAAAIAAAAAEACAAAAAAAAAEAAAAAAAAA
AAAAAAEAAAABAAAAAAAABQYLAAYGDQAECAsABA4LAAYIDQAGDQ4ABRINAAQWDAAEHg0ACAkSAAgO
EQAKCxUADA8XAAwMGQAODh0ACBARAAoUFgAIHBUADREbAA8QHQALHxoAEBEfAAYjEAAFJBAAByIU
AA0hFwAELxEACikXAAwiGwANJh4ADikeAA0vHQARLR8ABTESAAU0EgAIMRYADjMdAAw+GwASNB8A
EREhABEWIgATEyUAEhUlABUWKQAXGCwAGBguABEnIAASLSMAFC0jABQsJgAUMSIAEjUiABUyJAAV
NSUAETkgABM4JAAUOCUAFzUoAAdDGQAJRRsACEQcAAlNHwAHVhwAEEIhABZBJwAYRisAGkEtABxD
LwAZRSwAGEkqAApRIAAaUS0AEGQqABZnLgAKfSkAHmUzABtyNQAddjkACYApAA2BLAAKiiwADYsv
AAyRLwANjTAAFoE1ABmOOgANkzAAD5YyABGRNQARljYAEJg1ABKWOQARmDgAFJg4ABCjOQAUoTsA
Eaw8AA+wPAAeqkgAHrNKABu0SQAjrUsAJK5JACWuTQAlt08ALa1SACq2UgAus1QAKLlSACu9VAAs
vlUAMrpZACTIUgA0yF0APNhmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAD///8AQzU1MzU1QUNGQ0M1NTU1QzUDAQEDBzxJTUpAAwMDAzU1AwMBAQs8YHFWHAsBAQM1
NQMBCg4PGU9iPhEOCwEBNTUDAQsOKBVLZSAoFgsCATU1AQEPKCwSS2kgLCgOCwI6NQMLKCwsEk9u
LywoDw4OOjULAigsLR1Sbi8tLA8OCzo1AQIoLC0eVGszLiwPDgs6NQUCKCgsIFRuMiwoCw4CNTUR
CxYoKCBTbzMsKA4RCzo1JE5INSE8XXJCMyBHTB06NRhVa2tmYGFzcGZjZWonNTUHP1ldW1NRXV1d
WV1mQTU1AxcjIyMbGxsjIxsjJhdAQzU1QDU1NUA1NTVANUA1QwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAMAAAAGAAAAAB
ACAAAAAAAIAlAAAAAAAAAAAAAAAAAAAAAAAADx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8f
JP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k
/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/
Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/0SsXf9J
umX/RrBf/0u3bf9Lt23/S7dt/0u3bf9GsF//RrBf/0awX/9GsF//S7dt/0u3bf9Lt23/S7dt/0aw
X/9GsF//RrBf/0awX/9Lt23/S7dt/0u3bf9Lt23/RrBf/0awX/9GsF//RrBf/0u3bf9Lt23/S7dt
/0u3bf9GsF//RrBf/0awX/9GsF//S7dt/0u3bf9Lt23/S7dt/0awX/9GsF//RrBf/0awX/9Ltmz/
Tb1v/1XUef8PHyT/Dx8k/zqbV/8GBgr/BgYL/wUFCf8FBQn/BAQI/wUFCv8FBQn/BgYK/wYGCv8F
BQn/BgYK/wYGDP8HBwz/BwcM/wcHDf8HBwz/BgYL/wYGC/8GBgv/BwcN/wcHDP8GBgz/BgYM/wYG
C/8GBgv/BgYM/wYGC/8GBgv/BwcL/wcHC/8GBgv/BgYK/wYGC/8HBwz/BgYK/wUFCf8EBAj/BQUJ
/wYGC/8GBgv/BQUJ/wUFCf8FBQn/BQUJ/029b/8PHyT/Dx8k/0GgX/8GBgv/BgYL/wYGC/8FBQn/
BQUJ/wYGC/8GBgv/BQUJ/wQECP8FBQn/BwcM/wYGC/8GBgv/BwcM/wYGCf8EBAf/AwMG/wQEBv8D
Awb/AwMG/wMDBv8DAwb/BAQH/wQEB/8EBAf/AwMG/wMDBv8EBAb/BAQI/wQEB/8EBAf/BQUI/wYG
Cf8GBgv/BQUJ/wYGC/8GBgv/BgYL/wUFCf8FBQn/BQUJ/wYGC/8GBgr/BQUJ/0u2bP8PHyT/Dx8k
/0q1bP8GBgv/BQUJ/wYGC/8GBgr/BgYK/wYGCv8GBgr/BQUJ/wYGC/8GBgz/BgYL/wYGCv8HBw3/
BwcL/wQECP8DAwX/AwMF/wMDBf8CAgX/AgIE/wICBP8CAgT/AwMF/wMDBv8DAwX/AwMF/wICBP8D
AwT/AwMF/wICBP8CAgT/BAQI/wYGDP8ICA7/BgYM/wcHDP8GBgz/BgYL/wUFCf8HBwz/BgYL/wYG
C/8GBgv/BgYL/0awX/8PHyT/Dx8k/0u3bf8FBQn/BQUJ/wUFCf8FBQn/BQUJ/wYGC/8FBQn/BgYL
/wcHDf8HBwz/BwcM/wgIDv8KChH/BwcM/wMDBv8FLhH/BKM3/xjNU/8m0VD/LtZX/zDXWf8w11n/
Mdtl/zHbZf8x22X/M9xm/zrdYv9E5Gz/Ue15/1Tnev8gXTL/BAQG/wYGDP8JCQ//CAgP/wgIDf8G
Bgv/BQUK/wUFCv8GBgv/BgYL/wUFCf8FBQn/BgYL/0awX/8PHyT/Dx8k/0u3bf8FBQn/BQUJ/wYG
Cv8FBQn/BQUK/wUFCf8GBgr/BgYL/wcHDP8HBw7/CAgP/wkJEP8JCRD/CAgP/wUFCv8EBAb/BBQJ
/wd/KP8DrTX/GsxP/y7YX/8y22L/M9xm/zbeaP8+427/S+p4/1LufP8532j/B6w5/wMjDv8CAgT/
BQUI/wYGDP8HBw7/CAgO/wcHDf8HBwz/BwcM/wYGC/8FBQn/BQUJ/wYGC/8FBQn/BQUJ/0m1aP8P
HyT/Dx8k/0u3bf8HBwz/BgYL/wYGCv8HBwz/BgYK/wcHDP8HBwz/BwcM/wcHDv8ICA//CAgP/wkJ
Ef8JCRL/CwsV/woKFP8HBwz/BQUH/wYjD/8Kgib/Bpct/wzEQ/8u2F//OuBr/0jodv9S7n3/ON9q
/wS/Pf8ElC3/BBUL/wUFCP8GBgz/CAgO/wgIEf8KChH/CAgP/wcHDf8HBw3/CAgO/wcHDP8GBgv/
BQUJ/wcHDP8HBwz/BQUJ/0m1aP8PHyT/Dx8k/0awX/8GBgv/BQUJ/wUFCf8GBgv/BgYL/wYGC/8G
Bgr/BwcN/wgID/8ICA//CQkR/woKEv8KChP/DQ0W/w4OGf8KChP/BgYL/wMDBv8IZR//CoEm/wiN
K/8EwUT/Od1h/z/haP8gzEn/AbQr/wWkNv8EIA//BQUJ/wgIDv8KChL/CwsT/wwMFf8KChP/CAgP
/wgID/8ICA7/BwcM/wYGC/8GBgv/BgYL/wYGCv8GBgv/BgYL/0u3bf8PHyT/Dx8k/0awX/8FBQn/
BQUJ/wYGC/8GBgv/BgYL/wcHDP8ICA//CQkR/wsLE/8LCxP/CwsT/wwMFf8ODhn/DAwY/wwMFv8M
DBX/CQkQ/wUFCf8HPBX/CoEm/wqBJv8Iky7/D8I6/xXFP/8AuCv/AbEq/wRbIf8EBAj/BwcN/woK
E/8MDBb/DQ0Y/w4OGf8MDBb/CgoT/wsLE/8KChL/CAgP/wgIDv8ICA7/BwcN/wYGC/8FBQn/BQUJ
/0u3bf8PHyT/Dx8k/0m1aP8GBgv/BQUJ/wUFCf8GBgz/CAgO/woKEP8KChH/CAgQ/wsLE/8MDBX/
Dg4Y/xERHP8QEBz/Dg4b/w4OGv8NDRn/CwsV/wcHDf8GHg//CoEm/wqBJv8JiCn/BL89/xHHSP8E
vz3/ALI3/wUTDf8GBgz/CwsU/wwMF/8ODhr/EBAd/w4OGv8PDxr/Dw8Z/wsLFP8ICBD/CAgQ/wgI
EP8ICA//BgYN/wUFCf8GBgv/BQUJ/0u3bf8PHyT/Dx8k/0m1aP8GBgv/BgYL/wcHDP8HBw3/CAgO
/wkJEv8KChL/CgoS/wwMFf8NDRj/Dg4b/w4OGv8ODhr/EBAf/xQUIv8TEyD/DQ0a/wgIEP8GDQ3/
CoEm/wqBJv8JiSn/CsNC/xbKTP8OxUX/B4cw/wYGDP8KChP/Dw8c/xMTI/8SEiH/EBAe/w0NG/8M
DBb/DQ0Y/w4OGv8NDRf/CQkS/wkJEv8JCQ//CAgO/wcHDP8GBgz/BQUJ/0u4bf8PHyT/Dx8k/0u3
bf8FBQn/BQUJ/wcHDv8LCxP/CwsR/woKFP8ODhr/Dg4a/xISH/8UFCT/EREi/xQUJv8VFSX/ExMk
/xYWKP8ZGSv/EREf/wsLE/8HBwz/Cnkk/wqBJv8Iiif/FMtQ/x3PVv8YzVL/DVsp/wcHDf8RER3/
Fxco/xMTJP8VFSX/ExMi/xMTIv8XFyv/ExMk/xERH/8SEiH/EREf/w8PGf8MDBb/CwsU/woKEf8I
CA//BwcN/0exYP8PHyT/Dx8k/0u3bf8FBQn/BQUK/wYGDP8EBAr/AwMF/wMDBv8EBAf/BAQH/wUF
CP8EBAj/BQUI/wYGCv8HBwz/EBAe/xUVJv8VFSb/FBQl/w4OGf8HBw3/CXEj/wqBJv8IjSf/HtBW
/yLTWv8f0Vf/DD0g/wkJEP8SEiH/Fxcp/xISIv8UFCP/ExMk/wcHDP8GBgv/BgYK/wQEB/8EBAf/
AwMG/wMDBv8DAwb/AwMF/wQEB/8ICA//BgYL/0eyYP8PHyT/Dx8k/0u3bf8GBgr/BwcN/wkJDv8J
CRD/AwMF/wQEB/8EBAf/BgYL/wYGDf8HBw3/CAgO/wcHDv8GBgz/CgoV/xgYLP8YGC3/GRks/xER
Hf8EBAf/CGkg/wqBJv8HkSv/JtVd/ynWXv8m1V3/CCAQ/wgIDv8WFij/GRkv/xgYLP8YGCz/GBgq
/xERIP8GBgr/BQUJ/wYGC/8ICA//BQUL/wUFCv8FBQr/AwMF/wICBP8FBQr/BgYM/0q4av8PHyT/
Dx8k/0u3bf8GBgv/BwcN/wkJEP8KChH/AwMF/wMDBf8KChL/Dg4a/w8PG/8SEh//FBQj/xISIv8R
ESD/Dg4b/xgYKv8hITn/HBw0/wcHD/8CAgT/CGMe/wqBJv8Hli3/Ltli/y7ZYv8s2GH/CBkQ/wQE
B/8ODhr/ISE5/x4eNP8YGC3/FRUn/xAQH/8FBQr/BQUK/xcXKP8RER//Dg4Y/wsLFf8LCxP/CQkQ
/wUFCv8EBAj/BwcN/0q3af8PHyT/Dx8k/0awX/8GBgv/BgYM/wYGDf8ICBH/AwMG/wMDBv8ICBH/
EBAc/xAQHv8SEiD/EhIh/xISI/8WFib/FRUn/xcXKv8eHjf/EhIh/wQECP8DAwX/CWQg/wqBJv8H
mTH/Mthb/zDXWf8u1Vf/CRMS/wQECP8ICA//HR00/x8fN/8ZGS3/GRkt/xMTIv8HBwz/BgYL/xIS
Iv8QEB3/Dg4Z/wwMFf8LCxT/CgoR/wkJEP8ICA3/BgYM/0u4bf8PHyT/Dx8k/0awX/8HBwz/BwcN
/woKEv8QEBn/BAQI/wQECP8KChT/EBAd/xAQHv8SEiD/EREh/xQUJf8ZGSz/GRks/xsbMv8lJUH/
EREe/wUFCv8FBQr/CmUh/wqBJv8HnDL/Ndpe/zLYW/8w11n/DRcY/wsLFP8ICA//Fxcq/x8fNv8c
HDP/Hh42/xYWKP8ICA7/BgYM/xMTI/8TEyL/EREe/w4OGf8MDBX/CgoS/wkJD/8JCRH/BwcN/0u3
bf8PHyT/Dx8k/0m1aP8HBwz/BwcN/woKEv8MDBb/AwMG/wQECP8LCxb/EREd/w8PG/8RER//EhIh
/xISIv8XFyv/Gxsx/xwcMv8iIj3/CQkR/wUFCf8HBw7/Cmgi/wqBJv8GnjP/Nt1l/zPbY/8x2mH/
DBYW/wwMFv8HBw3/CgoS/x8fOf8cHDT/Hx85/xUVKP8ICA7/BgYM/xMTJP8RESD/EREe/w0NGP8L
CxP/CgoS/wkJEP8ICA//BwcO/0u3bf8PHyT/Dx8k/0m1aP8HBw3/BwcO/wcHD/8KChL/BAQG/wQE
CP8LCxb/EREe/xAQHv8TEyP/FRUm/xcXKf8XFyr/GBgs/xsbMv8iIj//CAgQ/wUFCv8JCQ//Cm4j
/wqBJv8GoTT/N95m/zPbY/8x2mH/DBYX/w0NGP8JCRD/CgoT/yEhPP8dHTP/HR0z/xUVJv8ICA7/
CAgO/xYWKP8ODhr/DAwX/wsLFP8KChP/CgoT/wkJEf8ICA7/BwcN/0u3bf8PHyT/Dx8k/0u3bf8I
CA3/CQkQ/woKEf8NDRf/BAQH/wQECP8NDRn/FRUl/xMTIf8TEyP/Fxcp/xgYK/8XFyr/GRkt/xwc
NP8hITv/FBQl/wcHC/8JCRD/CnUk/wqBJv8Fnyn/ON9q/zTdZ/8y22X/EBoc/wwMFP8KChL/FBQm
/ygoSP8eHjb/Gxsw/xQUJv8ICA7/CAgP/xgYKv8UFCP/EREe/w4OGv8PDxr/DAwW/woKEf8JCRD/
CAgO/0awX/8PHyT/Dx8k/0u3bf8GBgv/CAgO/woKEf8LCxP/BAQH/wQECP8MDBj/EBAe/xERIP8R
ESD/FBQk/xkZLv8dHTL/Hh42/x4eN/8gIDv/FBQo/wUFCv8EBAb/Cnsl/wqBJv8EoSn/Od9q/zTd
Z/8y22X/DRcY/wUFCf8JCQ//HBwy/yMjQf8eHjf/ISE6/xkZLv8ICA//BwcM/xQUKP8TEyL/EBAc
/w4OGv8PDxr/DQ0X/woKEv8HBw7/BwcN/0awX/8PHyT/Dx8k/0u3bf8GBgz/BgYM/wgIEP8ODhr/
BAQI/wQECP8MDBb/EREf/xUVJP8WFij/FBQk/xYWKv8YGCz/Ghow/yAgO/8iIj//Ghow/wcHD/8D
Awb/CoEm/wqBJv8EpjL/Od9q/zTdZ/8y22X/BxEN/wYGCv8RER3/JiZD/x0dNP8gIDr/JCRB/xgY
K/8ICA7/BgYM/xcXK/8UFCT/Dg4a/wwMFf8MDBb/CwsU/wkJEv8KChL/CAgP/0m1aP8PHyT/Dx8k
/0u3bf8ICA7/CAgO/wgIEP8NDRj/BAQH/wQEB/8NDRj/EhIh/xMTIv8UFCX/Fxcq/xgYLP8XFyn/
Fxcr/xoaL/8aGjD/Fxcs/w8PG/8FDAv/CoEm/wqBJv8DqDP/OeBq/zTdZ/8y22X/BhAM/wgID/8b
GzD/HR01/xsbM/8dHTT/Hx83/xYWKf8HBw7/CAgO/xkZLv8UFCT/EhIh/w8PGv8LCxX/CQkQ/woK
E/8KChH/CAgP/0m1aP8PHyT/Dx8k/0awX/8HBwz/CAgP/wsLE/8LCxP/BAQH/wQECP8NDRr/EREf
/w4OHP8QEB3/EhIi/xcXKv8dHTL/HR0y/xwcM/8cHDb/HR0z/xAQHf8LGBb/CoEm/wqBJv8ErTr/
ONxh/zPZXP8x11r/ChQS/w8PHP8cHDL/IiI8/yAgO/8dHTT/Gxsx/xcXK/8JCQ//CAgP/xgYK/8Q
EB//Dw8d/w8PGv8ODhr/DAwV/woKEv8HBw7/BwcM/0u3bf8PHyT/Dx8k/0awX/8GBgv/BwcN/woK
Ef8NDRj/BAQI/wUFCf8NDRj/Dw8b/xMTIP8WFif/FRUm/xcXK/8bGzH/HBwy/yAgOf8jI0D/Ghow
/w8PG/8LHhb/CoEm/wqBJv8EsDv/ONxh/zPZXP8x11r/DBYX/xERHv8dHTT/JydG/yUlQv8fHzr/
IiI9/xcXKf8ICA//CAgP/xcXKv8QEB7/Dg4a/wsLFP8MDBb/DAwW/woKE/8HBw7/BwcN/0u3bf8P
HyT/Dx8k/0m1aP8HBwv/BwcN/woKEf8NDRf/BAQH/wQEB/8KChL/EREf/xQUIv8UFCT/Fxcq/xYW
KP8UFCX/GRkt/xwcMv8ZGS//EhIi/woKE/8IIRL/CoEm/wqBJv8Eszz/ON5n/zPbY/8x2mH/ChQV
/w4OGv8YGCv/HBw0/xoaMf8YGCv/Gxsy/xcXKv8ICA//BwcO/xcXKf8TEyL/EBAd/w8PGv8LCxX/
CwsT/woKEv8JCRD/CAgP/0u3bf8PHyT/Dx8k/0m1aP8GBgz/BwcO/wkJEP8LCxX/AwMG/wQEB/8M
DBf/ExMi/xERHv8QEB7/EhIi/xUVJf8XFyr/Ghov/xsbMP8ZGS3/FRUn/wsLFP8JKRT/CoEm/wqB
Jv8Dtj7/ON5n/zPbY/8x2mH/ChQU/w4OGf8aGi//ICA6/xwcM/8dHTT/ICA4/xUVJ/8GBgz/BgYL
/xUVJ/8UFCT/EhIf/w4OG/8NDRf/CgoR/woKE/8KChL/CAgO/0u3bf8PHyT/Dx8k/0u3bf8HBw3/
BwcN/wkJDv8LCxL/BAQI/wUFCf8MDBb/EREd/xAQHf8QEB//EREg/xcXKf8aGi//GBgr/xYWKv8a
GjD/Fxcp/wwMFf8JMBj/CoEm/wqBJv8Bsir/OeBq/zTdZ/8y22X/CxUV/w8PG/8YGC7/HR0z/x8f
OP8bGzL/Gxsw/xERIf8HBw3/BwcN/xISIv8QEBz/Dg4a/wsLFf8LCxX/CQkR/wkJEP8KChH/BwcO
/0awX/8PHyT/Dx8k/0u3bf8GBgv/BgYK/wcHDf8GBgn/BAQG/wQEB/8FBQn/DAwV/w4OHP8SEh//
EREh/xMTI/8ZGSz/Fxcq/xYWKf8ZGS7/EhIi/wkJEP8INRf/CoEm/wqBJv8BtCv/OeBq/zTdZ/8y
22X/CxUV/w0NFv8UFCP/GRku/xkZL/8WFin/EhIh/wkJEv8ICA7/BwcN/wsLFf8MDBf/CwsU/wsL
FP8MDBT/CgoT/wcHDf8GBgz/BgYL/0awX/8PHyT/Dx8k/0u3bf8HBwz/BwcM/wYGCv8FBQj/BQUJ
/wcHDf8JCRP/DAwY/w4OGv8RER//ExMh/xISIv8WFif/GRkt/x0dM/8aGi7/EBAe/wgID/8JPBj/
CoEm/wqBJv8AvDr/OeBq/zTdZ/8y22X/CRMS/woKFP8UFCX/Hh41/xwcMf8XFyn/GRkr/xgYKv8S
EiH/EREf/w8PG/8KChP/BwcM/wcHDv8JCRH/CwsS/wkJEP8HBw3/BwcM/0m1aP8PHyT/Dx8k/0u3
bf8GBgr/BAQJ/wMDBf8DBAT/AwMF/wUFCv8ICA7/CgoT/w4OGv8ODhr/Dw8b/xMTI/8RESD/EREg
/xQUJf8UFCT/Dw8a/wkJD/8IQhn/CoEm/wqBJv8Cvjv/OeBq/zTdZ/8y22X/ChQT/w0NF/8UFCb/
GBgr/xgYLP8WFin/FBQl/xMTI/8TEyP/EREd/wkJE/8FBQn/AwQF/wQEB/8FBQr/BgYL/wgID/8I
CA//BgYM/0m1aP8PHyT/Dx8k/0awX/8FBQj/BAQH/wICA/8Zdzf/DBwS/wMDBf8FBQn/CAgO/wkJ
Ev8MDBb/Dg4Z/w8PHP8PDxz/EREe/xMTIf8TEyL/Dw8a/wcHDf8ISBn/CoEm/wqBJv8Hw0b/ONxg
/zPZXP8x11r/CRIQ/wsLFP8UFCT/FRUm/xISIv8VFSb/ExMh/w4OG/8ODhr/DQ0Y/wYGC/8DAwb/
HmIz/wwdE/8FBQn/BwcN/wcHDf8ICA7/BwcN/0u3bf8PHyT/Dx8k/0awX/8FBQj/BAQG/wICBP8E
Ux3/St90/yhtO/8FCQj/AwMF/wUFB/8ICA7/CQkQ/wkJEf8NDRb/Dg4Z/w8PGv8RER7/DQ0X/wYG
DP8IThv/CoEm/wqCJ/8LxUn/ONxg/zPZXP8z2Vz/CRMP/wgIDv8NDRj/EREd/w8PGv8PDxr/Dw8c
/wwMFf8ICA//BwcL/wQECP8EIg//Rd5w/yJdMv8DAwX/BQUK/wcHDv8HBw3/BgYK/0u3bf8PHyT/
Dx8k/0m1aP8FBQn/BAQI/wICBP8DFwr/Ar5B/07sev9L2nL/KnxB/xAtGv8DAwb/AwMH/wMDB/8F
BQr/BgYK/wYGDP8GBgz/BgYL/wUFCf8IVRz/CoEm/wmFKP8XzFH/QONu/z7ibP9F5nH/DBUT/wYG
C/8GBgr/BwcN/wcHDf8GBgv/BgYL/wQECf8EBAf/AwcH/wNHGv8DsTz/VfB//zWbUf8CAgT/BAQH
/wYGC/8HBwz/BQUJ/0u3bf8PHyT/Dx8k/0m1aP8GBgv/BAQH/wMDBf8CAgP/CHEi/xHJTf9N63j/
Tut4/0nodf8/0mj/L6VS/ySDQf8dbDb/GV4w/xVTKv8RSiP/BkUb/wVOHP8JdST/CoEm/wmKKv8j
01r/UOx6/1LufP9a8oL/OJVS/yZ1Pv8bYzP/FlUr/xJLJv8SVCf/El0p/xFtLv8MijP/ArQ+/wO6
P/8g0Vj/W/OD/0XYbf8DBAX/BAQH/wUFCv8FBQr/BgYK/0u3bf8PHyT/Dx8k/0u3bf8FBQn/BAQI
/wQEBv8CAgP/BkYW/wiJJ/8azlT/Sel2/0rpd/9G53T/QeJp/zzfZf843GH/Nttf/zXdaP8w2mT/
IdJY/wK/Qf8Fnin/CIwn/waVKP8l0E7/V/GB/131hf9d9YX/T+x6/zveZP8322D/NNpd/y/WWP8s
2GH/KNZe/yHSWP8XzFH/Cr40/w7BOf9F5G3/WPF//0npdv8QMRv/AwMF/wQECf8EBAj/BQUJ/0aw
X/8PHyT/Dx8k/0u3bf8FBQn/BgYK/wQECP8CAgT/BB4L/wqBJv8Ijiz/Gs5T/0Tmc/9I6HX/Q+Nr
/z/hZ/873mT/Od1h/zjfav8z3Gb/KNZe/xXLUP8AtSv/A6gq/wKqKv8cykb/Tux6/131hf9Y8YH/
SOh1/zzfZP863WL/N9tf/zLYW/8v2mP/LNhh/yXUW/8e0Fb/F8dB/ynSUv9X8H//Uu16/0rpdv8k
cTr/AgIE/wQEB/8FBQr/BQUJ/0awX/8PHyT/Dx8k/0u3bf8GBgr/BgYK/wQEB/8DAwX/AgMD/wl0
Iv8KgSb/CI8s/xfMUv9A5G//QuRv/z/jbf884Wr/O+Bp/zrga/823mj/K9dg/xrOVP8Evz3/ArI2
/wOtNf8BtTf/G85U/z7jbv9I6Hb/QuVx/z3ha/874Gr/Od9o/zTcZP8x22T/Ldlh/yTTW/8azlT/
EshI/yfUWf9O63j/TOp3/0rpd/84sVr/AQED/wMDBf8FBQn/BgYL/0m1aP8PHyT/Dx8k/0u3bf8F
BQr/BQUJ/wQECP8CAgT/AQEC/wZNGP8KgSb/CoEm/wiNK/8GozX/BKQy/wSlMv8EpTL/BKcz/wWq
OP8FqDf/BqI1/weZMf8Ijir/CYgo/wmGKP8Jhyj/CY0r/weXMP8GoDT/BqQ2/wSlMv8EpzP/BKcz
/wSmMv8FpTb/BqE0/webMf8IlC7/CI8r/waaLv8Kw0L/PeFr/0jodv9J5HT/Bg4J/wMDBP8FBQj/
BQUJ/0m1aP8PHyT/Dx8k/0awX/8FBQn/BgYL/wYGCv8EBAf/AgID/wQkDP8KgSb/CoEm/wqBJv8K
gSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqB
Jv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8JiCn/BLI8
/zTaXf9H5m//F0ck/wICA/8EBAj/BgYK/0u3bf8PHyT/Dx8k/0awX/8GBgr/BgYL/wYGC/8FBQj/
AwMF/wIEBP8JeST/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8K
gSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqB
Jv8KgSb/CoEm/wqBJv8KgSb/CoIn/wWdKf8jz03/JoQ+/wEBAv8DAwb/BQUK/0u3bf8PHyT/Dx8k
/0m1aP8FBQn/BQUJ/wUFCf8DAwf/AgIE/wEBAv8HUBj/CGId/wdMF/8GPxT/BTcS/wUuD/8FLA//
BSwP/wUsD/8FLA//BSwP/wUsD/8FLRD/BS0Q/wUtEP8FLA//BSwP/wUtEP8FLRD/BS0Q/wUtD/8F
LQ//BSwP/wUsD/8FLA//BSwP/wUsD/8FLA//BSwP/wUvD/8FNRH/BT0T/wZCFP8FWRv/Bogu/wIC
A/8DAwX/BAQI/0u3bf8PHyT/Dx8k/0m1aP8GBgv/BQUJ/wYGCv8HBwv/BAQI/wICBP8BAQL/AQEC
/wICA/8CAgT/AgIE/wICBP8CAgT/AwME/wMDBP8DAwT/AwME/wMDBP8DAwT/AwMF/wQEBv8EBAb/
BAQG/wMDBf8DAwX/AwMF/wQEBv8DAwX/AwME/wMDBf8DAwT/AwMF/wMDBP8CAgT/AgIE/wICBP8C
AgP/AgID/wICA/8CAgP/AQEC/wMDBP8FBQj/BgYK/0u3bf8PHyT/Dx8k/0y5bv8GBgv/BQUJ/wYG
Cv8GBgr/BQUK/wQECP8EBAb/AwMG/wMDBf8DAwb/BAQH/wQEB/8DAwf/BAQI/wUFCf8FBQj/BQUJ
/wUFCf8FBQj/BQUJ/wUFCf8FBQr/BQUK/wUFCf8FBQn/BQUJ/wUFCP8EBAj/BQUJ/wUFCv8FBQj/
BQUI/wUFCP8EBAj/AwMG/wQEB/8EBAf/BAQH/wQEB/8DAwX/AwMF/wMDBv8FBQr/BQUJ/0awX/8P
HyT/Dx8k/0y7bv8FBQn/BQUJ/wQECP8EBAj/BQUJ/wYGCf8EBAj/BAQI/wUFCv8FBQj/BQUI/wYG
Cf8GBgn/BwcL/wcHC/8GBgn/BwcL/wcHDf8HBwv/BgYK/wYGCv8GBgr/BgYK/wcHC/8HBwv/BwcL
/wYGC/8HBwv/BwcM/wYGCf8FBQn/BAQH/wUFCP8GBgr/BQUI/wQEB/8FBQj/BQUI/wYGC/8GBgv/
BQUJ/wYGCv8EBAj/BAQI/0m6Zf8PHyT/Dx8k/z6eXf9Mu27/TLlu/0m1aP9JtWj/SbVo/0m1aP9L
t23/S7dt/0u3bf9Lt23/SbVo/0m1aP9JtWj/SbVo/0u3bf9Lt23/S7dt/0u3bf9JtWj/SbVo/0m1
aP9JtWj/S7dt/0u3bf9Lt23/S7dt/0m1aP9JtWj/SbVo/0m1aP9Lt23/S7dt/0u3bf9Lt23/SbVo
/0m1aP9JtWj/SbVo/0u3bf9Lt23/S7dt/0q1bP9BoF//OptX/0exZ/8PHyT/Dx8k/w8fJP8PHyT/
Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8P
HyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8f
JP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k/w8fJP8PHyT/Dx8k
/w8fJP8PHyT/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAACAA
AABAAAAAAQAgAAAAAACAEAAAAAAAAAAAAAAAAAAAAAAAABQuKv8hUTj/IVA5/yNRPP8jUTz/IVA5
/yFPN/8hTzf/I1E8/yNRPP8iUDr/IU83/yFPN/8iUDr/I1E8/yNRPP8hTzf/IU83/yFQOf8jUTz/
I1E8/yFQOf8hTzf/IU83/yNRPP8jUTz/IlA6/yFPN/8hTzf/IlA6/yRWPv8WMy3/Hko1/ydhOP8b
Pyj/HEAq/xs/Kv8bPif/Gz4m/xo+Jf8dQSv/HUEs/x1AK/8cPyf/Gz4n/xxAKv8dQSz/HUEs/xs+
J/8bPif/Gz8p/x1BK/8dQSv/HD8o/xs+Jv8bPyf/HEAq/xs/Kf8cPyn/Gz4n/xo+Jf8bPyj/LW1C
/yRWPv8gTDn/Gjso/wUFCv8FBQn/BQUJ/wYGCv8EBAn/BQUJ/wYGC/8GBgv/BgYK/wQEB/8DAwX/
AwMF/wICBf8CAgX/AwMG/wMDBv8CAgX/AwMF/wMDBv8DAwb/BQUI/wYGC/8FBQr/BgYL/wUFCv8F
BQn/BQUK/wYGCv8cPyn/IlA6/yJRPP8cQCr/BQUJ/wUFCf8FBQn/BQUJ/wYGC/8GBgz/BgYM/wgI
Dv8FBQr/BBYK/wh3LP8Xizf/H487/yCQPP8hk0X/IZNF/ySTRP8sl0f/N51S/yFdMv8EBAj/BwcN
/wcHDf8GBgv/BQUK/wUFCv8FBQr/BQUJ/xs+J/8hTzf/I1E8/xxAK/8FBQn/BQUK/wUFCv8GBgr/
BgYL/wcHDf8ICA//CQkQ/wgID/8FBQn/BSoQ/wWJKv8Ywkn/LNdd/zfeaf9B5HD/QONv/yzOWv8F
WR//AwoI/wYGC/8HBw7/BwcN/wcHDP8HBwz/BQUK/wUFCf8FBQr/Gz8o/yJROv8hUDn/HD8o/wUF
Cf8GBgr/BgYK/wYGCv8HBw3/BwcO/wkJEP8JCRL/DAwW/woKEv8FCAn/B04Z/wiQK/8PukT/PN9n
/zbbYP8Ouz3/BGgj/wUJCv8ICA7/CgoS/woKEv8HBw7/BwcN/wcHDP8GBgv/BQUK/wYGC/8cQCr/
IlE7/yFPOP8bPif/BQUJ/wUFC/8HBwz/CAgO/wkJEf8LCxP/DAwV/w4OGf8MDBj/DAwW/wgID/8G
IxD/CoEm/wiKKv8Owj3/B742/wGMJ/8EGQ//CQkR/wwMFv8ODhn/DQ0Y/wsLFP8JCRL/CAgP/wgI
Dv8GBgz/BQUJ/xxAKv8jUTz/IlE6/xxAKv8FBQr/BgYM/wgID/8JCRH/CgoS/wwMFv8ODhr/Dg4a
/xAQHv8RER7/CgoV/wYPDv8KgSb/CYYo/wzEQ/8NxUX/BWcl/wcJD/8ODhv/EBAe/w8PHP8NDRj/
DQ0Y/wsLFf8ICBH/CAgP/wcHDP8GBgv/HEAq/yNRPP8jUTz/HEAq/wUFCv8ICA//CAgN/wkJEv8L
CxT/Dg4Z/w0NGv8QEBz/ExMj/xcXKP8QEB3/CAgP/wl5JP8Ihyb/Gc1T/xvPVP8LOB7/Dg4Y/xUV
Jv8UFCT/EREg/xAQHv8ODhn/DQ0X/wsLFf8JCRH/CAgO/wgIDv8cPyj/IU84/yNRPP8cQCr/BgYM
/wcHDf8DAwX/AwMG/wUFCv8FBQv/BgYM/wYGDP8PDx7/Fxcq/xQUJf8ICA//CHIi/wiKKP8k01v/
JNRb/wkeE/8QEB7/Fxcr/xYWKP8TEyP/CAgP/wUFCf8GBgv/BAQJ/wQECP8CAgX/BAQJ/xxAKv8i
UTr/IlA6/xxAKv8HBw3/CAgQ/wMDBf8HBw3/Dg4b/xERHv8SEiL/EhIi/xISIv8dHTP/EhIi/wMD
B/8IbSH/CI8r/y/YX/8t117/BhAN/wkJEf8fHzb/Ghov/xQUJv8JCRH/CgoT/xISIP8NDRf/CwsT
/wgIDv8FBQr/HUEr/yJRO/8hTzf/Gz8n/wcHDf8LCxT/AwMH/wcHD/8QEB3/EREf/xISIv8WFij/
GBgs/x8fOP8NDRf/BAQI/wluIv8Iki3/M9hc/zDWWf8KERT/CAgP/xsbMP8cHDL/GRku/wwMFf8K
ChP/EhIh/w8PGv8MDBX/CQkQ/wgID/8dQSz/I1E8/yJROv8dQSr/BwcO/woKE/8DAwb/CAgR/xAQ
HP8QEB7/ExMj/xUVKP8aGjD/Hx85/wcHDv8GBgz/CnEj/weVLv813GT/Mdph/wwSFv8JCRD/EREf
/x0dNf8bGzH/DAwW/wsLFP8RESD/Dg4a/wsLFP8JCRH/CAgP/x1BLf8jUTz/IlE7/x1BLP8ICA//
CwsT/wQEB/8JCRL/ExMh/xISIv8WFij/Fxcq/xkZLv8fHzn/DAwX/wgIDv8KdyT/BpUq/zbdZ/8y
22T/DRQY/woKEv8XFyv/ICA6/xkZLf8MDBb/DQ0X/xMTI/8ODhr/DQ0X/woKE/8JCQ//HUAq/yFQ
Of8jUTz/HUEr/wgIDv8LCxP/BAQH/wkJEv8RER//EhIi/xUVJv8aGi7/HR01/yAgO/8QECD/BAQH
/wp+Jf8Glyr/N95p/zLbZf8JDxD/CQkQ/x8fOf8fHzn/Hh43/w0NGP8LCxX/ExMk/w4OGv8NDRj/
CwsU/wgIEP8cQCn/IU84/yNRPP8dQS3/BwcO/wsLFf8EBAf/CQkS/xISIf8UFCT/FhYp/xcXKv8Z
GS7/HBw0/xQUJf8HCg3/CoEm/wWaLv833mn/Mttl/wYNDP8SEiD/Hh43/x0dNf8dHTT/DAwX/w0N
F/8VFSf/Dw8c/wwMFv8JCRH/CQkR/x1BLP8iUTr/IU83/xs/J/8ICA//CwsT/wQEB/8KChP/EBAd
/xERH/8UFCX/Ghov/xwcM/8eHjf/Fxcq/wwWGP8KgSb/Bp8z/zbbX/8x11r/DBMW/xgYK/8jIz7/
Hx84/xsbMf8NDRj/DQ0Y/xISIv8ODhr/DQ0Y/wsLFP8ICA//HUEs/yNRPP8iUDn/HEAp/wgIDv8M
DBX/BAQH/wgID/8RER7/FBQj/xYWKP8WFin/Gxsw/xwcNP8RESH/CRkU/wqBJv8GoTT/Ntxj/zHZ
X/8MEhf/FhYn/x8fOP8bGzL/Gxsx/w0NF/8MDBf/ExMj/w4OGv8MDBb/CgoT/wgIEP8eQi3/I1E8
/yJRO/8cQCv/BwcO/woKEv8DAwf/CQkR/xERH/8QEB7/ExMj/xcXKf8ZGS3/GRku/xISIf8JIBX/
CoEm/wSjMf823Wb/Mtpj/wsSFv8VFSf/Hh42/xwcM/8aGi//CgoU/woKFP8TEyL/Dw8b/wwMF/8J
CRH/CQkR/x1BLP8iUDr/I1E8/x1BLP8GBgv/BwcM/wQEB/8GBgv/Dg4Z/xAQHv8SEiL/Fxcq/xYW
Kv8YGCz/EBAe/wglFf8KgSb/BKIp/zffaf8y22X/CxIV/xISIf8aGjD/GBgu/xERIf8JCRD/CQkR
/w0NGP8LCxX/CwsU/wkJEP8HBw3/Gz4n/yFPN/8jUTz/HUEr/wUFCv8EBAf/BQUJ/wcHD/8MDBf/
Dw8c/xERIP8TEyP/Fxcq/xgYK/8NDRj/CCwV/wqBJv8DqDP/N99p/zLbZf8JEBP/EREf/xsbMP8Y
GCv/Fxco/xMTI/8PDxz/CQkS/wUGCv8HBw3/CQkP/wcHDv8cQCr/IlE6/yFQOf8bPyf/AwMG/ww2
Gv8HDgv/BQUJ/wkJEf8MDBb/Dw8b/w8PHf8RER//ExMi/wwMFf8HMRX/CoEm/warOP823GL/Mtle
/woQEv8RER//FRUm/xQUJv8SEiD/Dw8d/wsLFf8EBAn/ETMc/wYKC/8GBgz/BwcO/x1BLP8iUTv/
IU84/xs+Jv8DAwX/AyoQ/zK/XP8kZjf/DSMV/wcKDP8HBw3/CQkQ/wsLFP8MDBf/CQkQ/wc3Ff8J
gSb/DbA//zndY/843GL/CQ8P/wkJEf8NDRf/DAwV/wsLFP8HBw3/BQ0L/wM/GP8/vWL/DycX/wUF
Cv8GBgz/HEAq/yNRPP8iUTr/HEAp/wMDBv8CBgX/EKM8/z/fbf8+vGD/LpZM/x1nNf8WTin/ET4i
/w41HP8FMRX/B1gd/wmDJ/8XuEf/Sul2/1Dsev8kYTf/Fkgn/xA4H/8OOB3/DUMf/wpWI/8Cgi7/
D7VF/1Did/8XQyT/BAQI/wUFCv8cQCr/I1E8/yNRPP8cQCr/BAQI/wICBP8GUhn/EKc8/z7ibv9H
53T/QOFo/zrdY/823GL/Mttm/xrNU/8FrzP/BZco/xi9P/9X8YD/W/SE/0bmcf853GH/M9lc/y7Y
Xv8n1V3/HM9U/xHCO/853GL/Ue16/yd8QP8DAwX/BAQI/xo+Jf8hTzf/I1E8/xxAKv8FBQn/AwMF
/wQwD/8JgSb/FrRF/znfav9B42z/POBp/zrfZ/823mj/JNNb/wnBQP8CrTH/B7Y4/zXdZ/9L6nj/
QeRv/zvfZ/823GP/Mdpi/ynWX/8e0Fb/GstL/0Pkbv9M6nf/ObVc/wICBP8EBAj/Gz8o/yJQOf8i
UDr/Gz8p/wUFCf8DAwb/AhYI/whrIP8Jgyf/B5It/waYLv8GmS7/Bpsv/wabMf8HlS//CIwq/wmF
J/8JhCf/CIsq/weTLv8GmC//Bpku/waaLv8GmS//B5Uu/wiPLP8IjCr/CKU0/zHXYf9G5HD/CBYN
/wQEBv8cQCn/IlE7/yFPN/8bPib/BgYK/wUFCP8CBgX/B1ca/wqBJv8KgSb/CoEm/wqBJv8KgSb/
CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8KgSb/CoEm/wqBJv8J
gib/DJwy/ybKTv8WSiT/AgIF/xxAK/8jUTz/IlE6/xs/Kf8FBQn/BAQI/wICBP8DJAz/BTwS/wQt
D/8EIwz/BB4L/wQeC/8EHgv/BB4L/wQeC/8EHwz/BB4M/wQeDP8EHwz/BB8M/wQfC/8EHgv/BB4L
/wQeC/8EHgv/BB4L/wQiDP8EKg3/BDYR/wM9Fv8DAwX/HEAq/yNRPP8jUTz/HUEr/wUFCf8GBgr/
BAQI/wMDBf8CAgT/AgIF/wMDBv8CAgb/AwMG/wQEBv8EBAf/BAQG/wQEB/8EBAj/BAQI/wQEB/8E
BAf/BAQH/wQEB/8EBAf/BAQG/wMDBv8CAgX/AwMF/wMDBf8CAgT/AgIE/wQECP8bPyf/IVA5/yFP
Ov8qZj//HEAp/xs/KP8bPyj/Gz8p/xs/Kv8cQCr/Gz8o/xxAKP8dQSr/HUEq/x1BLP8dQSv/HEAp
/xxAKf8dQSv/HUEr/x1BK/8cQCr/HEAq/xxAKf8bPyn/HEAq/xs/J/8bPyf/HEAp/x1BK/8cQCr/
GTom/yZhOP8iUTn/FC0q/yFPOv8jUTz/IlE6/yJROv8iUTv/I1E8/yNRPP8iUTr/IlE6/yJRO/8j
UTz/I1E8/yJRO/8iUTr/IlE6/yNRPP8jUTz/IlE7/yJROv8iUTr/IlE7/yNRPP8jUTz/IlE6/yJR
Ov8iUTv/I1E8/yJRPP8gTDn/Hko2/xUvK/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAQAAAAIAAAAAEAIAAA
AAAAQAQAAAAAAAAAAAAAAAAAAAAAAAAeSjP/Hkgx/x5HMf8dRi7/IEkz/x9HMP8eRzD/IEk0/x5G
L/8fSDL/H0gy/x5GLv8fSDL/Hkcw/x5HL/8iUzr/HkYx/wUFCf8FBQn/BQUK/wYGDP8ECQn/CUIb
/xBIIP8SSyX/FUsl/xdAJP8FBQr/BgYL/wUFCf8FBQn/Hkcw/x9IMv8FBQn/BQUK/wYGDP8ICBD/
CAgQ/wVCF/8WuEX/Ot9o/x+1Sv8FHQ//CAgP/wcHDf8GBgv/BQUK/x5IMf8eRzD/BQUK/wgIDv8K
ChP/DQ0Y/w4OGv8HERD/CYQn/wvCPv8ERRr/DAwY/w0NGf8LCxT/CAgP/wYGC/8fSDP/H0gz/wYG
DP8FBQr/CAgQ/woKE/8UFCT/DQ0Y/wh/Jf8f0Ff/DB0Z/xUVJ/8PDxz/CQkR/wcHDf8FBQr/Hkcx
/x5HMP8ICA//BQUK/xAQHf8TEyP/GRku/wkJEv8Ifyb/L9dc/wgMEP8cHDH/EBAe/w4OGf8MDBb/
BwcN/x9JM/8fSTL/CQkQ/wYGDP8RER//FRUn/xwcNP8ICA//CIQn/zPbZP8LDhT/GRku/xMTIv8P
Dxv/DQ0X/wkJEP8fSDP/IEk0/wkJEf8GBgz/EhIh/xcXKf8cHDT/CwwW/weMKP803Gf/Cg0T/x4e
N/8VFSb/EBAd/w0NGf8JCRH/H0gx/x5HMP8JCRH/BgYM/xERH/8WFin/HBwz/w8VHf8IkCz/M9le
/xEUH/8fHzj/FBQk/w8PHf8NDRj/CQkR/yBJNP8fSDP/BwcN/wUFCv8PDx3/FBQm/xgYLP8MGRr/
B5Ep/zTcZf8PEhz/Gxsx/w8PHf8MDBf/DAwW/wgID/8eRzH/H0gx/wYQDP8GBwv/DAwW/xAQHv8U
FCX/Ch0V/weVLf8022P/DRAY/xcXKf8SEiL/CQkT/wgSD/8HBw3/H0gy/x5HMP8CDQj/KalP/yBf
M/8QMR7/DSIa/wcyFf8NmzT/QuNt/xMwH/8NIhr/CioY/wZgJf8tgkX/BQUK/x9IM/8fSDP/AwMG
/whqIv8112T/PeBo/zbdZf8TxEj/Ca00/0zreP8+4Wr/Mtlf/yLSWf8p01X/P8Jj/wMDBv8eRy//
Hkcw/wQECP8ENxH/CYUo/wiMKv8Ijiv/CIgp/wmCJv8IiCn/CIwq/wiNKv8IiSn/CI0q/yrIVP8J
GQ//H0gy/x9IMv8FBQn/AwsH/wMbCv8DEQj/AxAI/wQRCP8EEQn/BBEJ/wQRCf8EEQn/AxAI/wMR
CP8DGQn/AxEJ/x5IMf8gTDf/H0gx/x5IMf8fSDP/Hkgx/x9JMv8fSTP/H0gx/yBJM/8fSDL/H0gy
/x9IMv8eSDD/H0gy/x1FMf8eSjT/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')
	#endregion
	$LoLUpdater.Name = "LoLUpdater"
	$LoLUpdater.Text = "LoLUpdater"
	$LoLUpdater.add_Load($LoLUpdater_Load)
	#
	# buttonNothing
	#
	$buttonNothing.Location = '13, 190'
	$buttonNothing.Name = "buttonNothing"
	$buttonNothing.Size = '131, 23'
	$buttonNothing.TabIndex = 7
	$buttonNothing.Text = "Nothing"
	$buttonNothing.UseVisualStyleBackColor = $True
	$buttonNothing.add_Click($buttonNothing_Click)
	#
	# buttonRestore
	#
	$buttonRestore.Location = '13, 160'
	$buttonRestore.Name = "buttonRestore"
	$buttonRestore.Size = '131, 23'
	$buttonRestore.TabIndex = 6
	$buttonRestore.Text = "Restore"
	$buttonRestore.UseVisualStyleBackColor = $True
	$buttonRestore.add_Click($buttonRestore_Click)
	#
	# buttonPatch
	#
	$buttonPatch.Location = '13, 129'
	$buttonPatch.Name = "buttonPatch"
	$buttonPatch.Size = '131, 23'
	$buttonPatch.TabIndex = 5
	$buttonPatch.Text = "Patch"
	$buttonPatch.UseVisualStyleBackColor = $True
	$buttonPatch.add_Click($buttonPatch_Click)
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($checkboxCleanTemp)
	$groupbox1.Controls.Add($checkboxWindowsUpdate)
	$groupbox1.Controls.Add($checkboxDeleteOldLogs)
	$groupbox1.Controls.Add($checkboxDefrag)
	$groupbox1.Location = '13, 12'
	$groupbox1.Name = "groupbox1"
	$groupbox1.Size = '131, 111'
	$groupbox1.TabIndex = 4
	$groupbox1.TabStop = $False
	#
	# checkboxCleanTemp
	#
	$checkboxCleanTemp.Location = '6, 19'
	$checkboxCleanTemp.Name = "checkboxCleanTemp"
	$checkboxCleanTemp.Size = '119, 24'
	$checkboxCleanTemp.TabIndex = 0
	$checkboxCleanTemp.Text = "Clean Temp"
	$checkboxCleanTemp.UseVisualStyleBackColor = $True
	$checkboxCleanTemp.add_CheckedChanged($checkboxCleanTemp_CheckedChanged)
	#
	# checkboxWindowsUpdate
	#
	$checkboxWindowsUpdate.Location = '6, 80'
	$checkboxWindowsUpdate.Name = "checkboxWindowsUpdate"
	$checkboxWindowsUpdate.Size = '119, 24'
	$checkboxWindowsUpdate.TabIndex = 3
	$checkboxWindowsUpdate.Text = "Windows Update"
	$checkboxWindowsUpdate.UseVisualStyleBackColor = $True
	$checkboxWindowsUpdate.add_CheckedChanged($checkboxWindowsUpdate_CheckedChanged)
	#
	# checkboxDeleteOldLogs
	#
	$checkboxDeleteOldLogs.Location = '6, 40'
	$checkboxDeleteOldLogs.Name = "checkboxDeleteOldLogs"
	$checkboxDeleteOldLogs.Size = '104, 24'
	$checkboxDeleteOldLogs.TabIndex = 1
	$checkboxDeleteOldLogs.Text = "Delete old logs"
	$checkboxDeleteOldLogs.UseVisualStyleBackColor = $True
	$checkboxDeleteOldLogs.add_CheckedChanged($checkboxDeleteOldLogs_CheckedChanged)
	#
	# checkboxDefrag
	#
	$checkboxDefrag.Location = '6, 59'
	$checkboxDefrag.Name = "checkboxDefrag"
	$checkboxDefrag.Size = '61, 24'
	$checkboxDefrag.TabIndex = 2
	$checkboxDefrag.Text = "Defrag"
	$checkboxDefrag.UseVisualStyleBackColor = $True
	$checkboxDefrag.add_CheckedChanged($checkboxDefrag_CheckedChanged)
	$groupbox1.ResumeLayout($false)
	$LoLUpdater.ResumeLayout($false)
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $LoLUpdater.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$LoLUpdater.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$LoLUpdater.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $LoLUpdater.ShowDialog()

} #End Function

#Call the form
Call-LoLUpdater_psf | Out-Null
